version: '3.2'
services:
  db:
    image: timescale/timescaledb:latest-pg14
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    network_mode: bridge
    ports:
      - "6379:6379"
